/* Automatically generated by build/gen.js*/
import Button from './button';

const components = {
  Button
};

const YoUI = {
  install(Vue) {
    Object.keys(components).forEach(key => {
      Vue.component(components[key].name, components[key]);
    });
  }
};

// prettier-ignore
export {
  YoUI as default,
  Button
};

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(YoUI);
}
